# Generated by Django 4.2.27 on 2025-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_file_name_chatmessage_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='file_path',
            new_name='storage_path',
        ),
    ]
