# Generated by Django 4.2.10 on 2026-01-11 15:32

import django.contrib.postgres.fields
from django.db import migrations, models
import logging_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0002_add_start_end_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsupplementitem',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='foodsupplementitem',
            name='reminder_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='foodsupplementitem',
            name='reminder_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=logging_app.models.default_reminder_days, size=None),
        ),
    ]
