# Generated by Django 4.2.10 on 2026-01-11 16:46
# This migration ensures the reminder_times field is properly configured with db_column

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0003_multiple_reminder_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsupplementitem',
            name='reminder_times',
            field=models.JSONField(blank=True, db_column='reminder_times', default=list),
        ),
    ]
